// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byankhnmqnewhdcvsoyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5YW5raG5tcW5ld2hkY3Zzb3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NTg5ODAsImV4cCI6MjA1ODQzNDk4MH0.T4i1-ofCC1Tjm9TAklo5xdj77ggrsXqNBv3GtPwsOm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);