
name: Version Bump

on:
  push:
    branches: [ main ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Get current version from vite.config.ts
      - name: Get current version
        id: get_version
        run: |
          VERSION=$(grep -o 'VITE_APP_VERSION.*".*"' .env || echo 'VITE_APP_VERSION="1.0.0"')
          VERSION=${VERSION##*\"}
          VERSION=${VERSION%%\"*}
          echo "::set-output name=current_version::$VERSION"
          
      # Increment patch version
      - name: Increment version
        id: increment_version
        run: |
          IFS='.' read -ra VERSION_PARTS <<< "${{ steps.get_version.outputs.current_version }}"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=$((${VERSION_PARTS[2]} + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "::set-output name=new_version::$NEW_VERSION"
      
      # Create or update .env file with new version
      - name: Update version in .env
        run: |
          echo "VITE_APP_VERSION=\"${{ steps.increment_version.outputs.new_version }}\"" > .env
      
      # Commit and push changes
      - name: Commit and push version change
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .env
          git commit -m "Bump version to ${{ steps.increment_version.outputs.new_version }}"
          git push
